#!/bin/bash

echo "========================================="
echo "FIX: File Watcher Limit Issue"
echo "========================================="
echo ""
echo "The error 'ENOSPC: System limit for number of file watchers reached'"
echo "means your system needs to increase the file watcher limit."
echo ""
echo "SOLUTION 1: Increase file watcher limit (RECOMMENDED)"
echo "Run this command:"
echo ""
echo "  echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p"
echo ""
echo "Or manually:"
echo "  1. sudo nano /etc/sysctl.conf"
echo "  2. Add this line at the end: fs.inotify.max_user_watches=524288"
echo "  3. Save and exit (Ctrl+X, Y, Enter)"
echo "  4. Run: sudo sysctl -p"
echo ""
echo "========================================="
echo "SOLUTION 2: Temporary fix (until reboot)"
echo "Run this command:"
echo ""
echo "  sudo sysctl fs.inotify.max_user_watches=524288"
echo ""
echo "========================================="
echo "SOLUTION 3: Clean up node_modules (if above doesn't work)"
echo "Run these commands:"
echo ""
echo "  cd /home/nell/Downloads/WashBox/mobile"
echo "  rm -rf node_modules"
echo "  npm install"
echo ""
echo "========================================="
echo ""
echo "After applying the fix, restart Expo:"
echo "  npx expo start"
echo ""
